include: package:very_good_analysis/analysis_options.3.0.0.yaml
linter:
  rules:
    directives_ordering: false
    public_member_api_docs: false
analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/generated/**