name: shopping_cart
description: A simple cart app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  badges: ^2.0.3
  bloc: ^8.0.3
  cached_network_image: ^3.2.1
  equatable: ^2.0.3
  faker: ^2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  go_router: ^3.1.0
  hydrated_bloc: ^8.1.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  path_provider: ^2.0.10

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  import_sorter: ^4.6.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  test: ^1.21.1
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true