name: shopping_cart
description: A simple cart app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  equatable: ^2.0.3

  path_provider: ^2.0.10

  # Environment
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.0.3

  logger: ^1.1.0

  # Router
  go_router: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.1
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true